module.exports = `
  INSERT INTO products (category_id, product_name, price, description, video_url, image_url) VALUES (1, 'Pipe Dreams', 29.00, '24 shots- gold palms with red and green glitter, then brocade with red and green falling leaves to blue stars. to delayed crackling with multicolored stars, and silver flying fish with red glitter. 5 shot finale of jumbo gold palms with red and green glitter. 4 shot finale.', 'https://www.youtube.com/embed/xasx_KNmjpU', 'https://drive.google.com/uc?export=view&id=1dWhcF0182tIAU-AHGiaBui0OMFxkAJxg');
  INSERT INTO products (category_id, product_name, price, description, video_url, image_url) VALUES (1, 'Diamond Mine', 29.00, 'You will love these diamonds glittering in the sky with 24 shots of pure beauty. The whole sky will look like a mine with flashes of vibrant red, crystalwhite, and glowing green. Along with the sparkling white strobing shells. Plus the end of this beauty includes a pounding finally of three shell counts at once. Its hard to believe this cake is 200 grams. From Mad Ox Fireworks', 'https://www.youtube.com/embed/p-Dxfmx7rno', 'https://drive.google.com/uc?export=view&id=1_HmYR1D85dkhk22d0-nPQGFdgHrwAyxF');
  INSERT INTO products (category_id, product_name, price, description, video_url, image_url) VALUES (1, 'Whirlwind of the Caribbean', 20.00, 'Red, green, and blue tail to strobing star with 19 shots and silver swirling with a red, green, and blue heart.', 'https://www.youtube.com/embed/leR-mbO_WXA', 'https://drive.google.com/uc?export=view&id=1vzxBJjaIy1BYL6tANbSi9eacfOZ1gfIS');
  INSERT INTO products (category_id, product_name, price, description, video_url, image_url) VALUES (1, 'Epicenter', 23.00, 'Dominator Epicenter - This item features 12 multi-level effects with colorful mines bursting into large and loud star bursts above. With so much power, you will think your at the center of an Earthquake!', 'https://www.youtube.com/embed/iYfZPtu2OcE', 'https://drive.google.com/uc?export=view&id=1jhDoJ0lotmbAeQTZlHkityEMJmMBMQXt');
  INSERT INTO products (category_id, product_name, price, description, video_url, image_url) VALUES (1, 'Nuc-em', 24.00, 'Nuc-Em Performance: 16 Shots of radioactive colors. Fills the sky with bright color hard hitting peony breaks!', 'https://www.youtube.com/embed/uXxC5-e-Z3E', 'https://drive.google.com/uc?export=view&id=18tyBeBteJXY9EGdx-oPk7XBVn6lbJHWm');
  INSERT INTO products (category_id, product_name, price, description, video_url, image_url) VALUES (2, 'Battleship - 43 Shots', 57.00, 'A great battle rages from this giant cake - over 17 inches long! Get 43 shots of red, green, and lemon stars, red and green strobe, silver spinners, and crackling.', 'https://www.youtube.com/embed/9QclYPoRJO0', 'https://drive.google.com/uc?export=view&id=1OD-Y9UAMpxnaiuLRShtcmTEwbYelHNNI');
  INSERT INTO products (category_id, product_name, price, description, video_url, image_url) VALUES (2, 'Notorious - 33 Shots', 63.00, 'Notorious is infamous for its brocade willow with colorful tips and double-layered timerain mine. Ends with a barrage of powerful screamers. A great show at a great price!', 'https://www.youtube.com/embed/o-1eVnZcTbY', 'https://drive.google.com/uc?export=view&id=1IEGn9esFT-SCrHKEfI4zMY7tTmSza7hf');
  INSERT INTO products (category_id, product_name, price, description, video_url, image_url) VALUES (2, 'Super Stallion', 18.00, 'A Brothers classic! One of the best deals in fireworks, Super Stallion puts on a show of color-changing breaks, crackling and report. Duration: 25 seconds.', 'https://www.youtube.com/embed/ubkjv5ITdlw', 'https://drive.google.com/uc?export=view&id=1rwQZdKZI4vtU-nNnPmMrYMHEnjBuUmyM');

  `;